steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_APP_URL=https://compakt-iewrqe7jkq-uc.a.run.app
      - --build-arg
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - --build-arg
      - CLERK_SECRET_KEY=${_CLERK_SECRET_KEY}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET=${_NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET}
      - --build-arg
      - SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY}
      - --build-arg
      - NEXT_PUBLIC_GIT_SHA=${_NEXT_PUBLIC_GIT_SHA}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/compakt-488215/compakt/compakt:c1630bc
  _NEXT_PUBLIC_GIT_SHA: c1630bc
  _NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ""
  _CLERK_SECRET_KEY: ""
  _NEXT_PUBLIC_SUPABASE_URL: ""
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: ""
  _NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET: dj-media
  _SUPABASE_SERVICE_ROLE_KEY: ""
